# -*- ruby -*-

# DO NOT EDIT THIS FILE. Instead, edit Rakefile, and run `rake bundler:gemfile`.

source "https://rubygems.org/"

gem "yard", ">=0", :group => [:development, :test]
gem "redcarpet", ">=0", :group => [:development, :test]
gem "github-markdown", ">=0", :group => [:development, :test]

# vim: syntax=ruby

